# Generated by Django 3.2.5 on 2021-10-17 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('titles', models.CharField(max_length=20, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('post_kind', models.CharField(blank=True, choices=[('BLOG', 'BLOG'), ('ADVERTISING', 'ADVERTISING'), ('NEWS', 'NEWS')], max_length=11, null=True, verbose_name='Тип поста')),
                ('is_moderated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
