# Generated by Django 3.2.5 on 2021-10-26 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_blog_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('posts', 'owner')},
        ),
    ]
